---
- name: Monitor Cisco ACI environments
  hosts: aci
  gather_facts: no
  connection: local

  tasks:
    - name: Get Spine&Leaf CPU information
      cisco.aci.aci_rest:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no
        method: get
        path: /api/node/class/procSysCPU5min.json?order-by=procSysCPU5min.userAvg|desc&page-size=2000 
      register: health_info

    - name: Print tenant health information
      debug:
        msg: "{{ health_info }}"